Vazkii/Patchouli

README.md

Took me like 10 minutes to see this and I was very confused why everything broke

Fix maven artifact

---

src/main/resources/assets/patchouli/lang/pl_PL.lang

It doesn't have this issue: https://github.com/Vazkii/Patchouli/issues/22

Added Polish translation

---

src/main/resources/assets/patchouli/lang/en_US.lang

Well, Subtitles Are Now Localised

Sounds Subtitles Need Localization Fixed

---

src/main/resources/assets/patchouli/lang/it_IT.lang

Added Italian localization

---

src/main/java/vazkii/patchouli/client/book/BookContents.java
src/main/resources/assets/patchouli/lang/pl_PL.lang

https://github.com/Vazkii/Patchouli/issues/22#issuecomment-438760594

Update pl_PL.lang and remove package, which doesn't exist

---

src/main/java/vazkii/patchouli/common/util/ItemStackUtil.java

Fix ItemStackUtil.serializeStack not serializing the stack size

---

src/main/java/vazkii/patchouli/client/book/BookContents.java
src/main/java/vazkii/patchouli/client/book/ClientBookRegistry.java

Fall back to landing page when book is unable to open due to the current page becoming unopenable

---

src/main/java/vazkii/patchouli/client/book/page/PageMultiblock.java
src/main/java/vazkii/patchouli/common/multiblock/Multiblock.java

- Render blocks as they would appear in the world
- Diffuse lighting
- Contextual states
- Fluids work now
- Implement block layers, only one draw call per layer
- Translucent layer is depth sorted properly
- Render TESRs as well as possible
- TESRs are sorted into the block rendering properly
- TESRs are **NOT** given a fake world, so any world access they might do during rendering will not be accurate
- To accomodate potential issues with this and the whole rendering strategy, all exceptions are caught and logged once
Comparisons:
Before (no diffuse lighting): 
After (with diffuse lighting):
Before (without depth sorting):
https://i.imgur.com/w2tkems.gifv
After (with depth sorting):
https://i.imgur.com/5CP0LnC.gifv
Example of TESRs and contextual rendering (sorting was still broken …

Improve multiblock rendering

---

src/main/java/vazkii/patchouli/api/IStateMatcher.java
src/main/java/vazkii/patchouli/api/stub/StubMatcher.java
src/main/java/vazkii/patchouli/client/gui/GuiAdvancementsExt.java
src/main/java/vazkii/patchouli/common/multiblock/Multiblock.java
src/main/java/vazkii/patchouli/common/multiblock/StateMatcher.java
src/main/java/vazkii/patchouli/common/util/ItemStackUtil.java

Self explanatory from commit messages.

Some 1.14 tweaks

---

build.gradle
src/main/java/vazkii/patchouli/client/book/BookCategory.java
src/main/java/vazkii/patchouli/client/book/BookEntry.java
src/main/java/vazkii/patchouli/client/book/BookPage.java
src/main/java/vazkii/patchouli/client/book/page/PageImage.java
src/main/java/vazkii/patchouli/client/book/page/PageLink.java
src/main/java/vazkii/patchouli/client/book/page/PageQuest.java
src/main/java/vazkii/patchouli/client/book/page/PageRelations.java
src/main/java/vazkii/patchouli/client/book/page/PageSpotlight.java
src/main/java/vazkii/patchouli/client/book/page/abstr/PageDoubleRecipe.java
src/main/java/vazkii/patchouli/client/book/template/component/ComponentHeader.java

Basically all text I could find in pages is now translated for i18n-enabled books.

Missed I18n support for all the things

---

src/main/java/vazkii/patchouli/client/book/BookEntry.java
src/main/resources/data/patchouli/patchouli_books/testbook1/en_us/entries/intro/smelttest.json

For things like Botania livingwood, etc that are described through text and not shown on a template.

Allow putting additional recipe mappings through the json

---

Jenkinsfile

Fixes automatic builds for Jared's maven.

Remove sDecW step from 1.14 jenkinsfile

---

src/main/java/vazkii/patchouli/api/stub/StubMultiblock.java

Fix compiler errors after last api change

---

src/main/java/vazkii/patchouli/api/PatchouliAPI.java
src/main/java/vazkii/patchouli/api/stub/StubPatchouliAPI.java
src/main/java/vazkii/patchouli/common/base/PatchouliAPIImpl.java
src/main/java/vazkii/patchouli/common/multiblock/StateMatcher.java

this is useful for blocks like the lever or lectern to only check the direction property

add filtering StateMatcher

---

src/main/java/vazkii/patchouli/client/base/ClientAdvancements.java
src/main/java/vazkii/patchouli/common/book/Book.java

Turns out vanilla has something exactly for this purpose! How nice of them.

Fix duplicate book toasts for quickly unlocked entries of the same book

---

src/main/java/vazkii/patchouli/api/IVariable.java
src/main/java/vazkii/patchouli/client/book/page/PageCrafting.java
src/main/resources/data/patchouli/patchouli_books/comprehensive_test_book/en_us/entries/recipe_mapping/recipe.json

Fixed shapeless icon on crafting pages

---

src/main/java/vazkii/patchouli/api/VariableHelper.java
src/main/java/vazkii/patchouli/client/book/template/component/ComponentItemStack.java
src/main/java/vazkii/patchouli/client/book/template/variable/GenericArrayVariableSerializer.java
src/main/java/vazkii/patchouli/client/book/template/variable/ItemStackArrayVariableSerializer.java
src/main/java/vazkii/patchouli/client/book/template/variable/VariableHelperImpl.java

Add Variable.as() specializations for arrays; reimplement tags

---

src/main/java/vazkii/patchouli/client/book/gui/GuiBook.java
src/main/java/vazkii/patchouli/client/book/gui/button/GuiButtonBookMarkRead.java

Also books can now be closed with the Inventory keybind.
Removed button from the Index page since it doesn't do anything there.
~I still want to test this with the respective book first if it's possible.~

Added a check to the markCategoryAsRead method to prevent overflow

---

src/main/java/vazkii/patchouli/client/book/text/SpanState.java

Caused by: I put the call at the wrong spot, F

Fix styling issue with links for real this time

---

src/main/java/vazkii/patchouli/client/book/gui/GuiBook.java
src/main/java/vazkii/patchouli/client/book/gui/GuiBookEntry.java

Fixes #419
Also changed the logic for when the markAsReadButton should appear a little : )
I can't believe I didn't test this properly the first time :/

Fixed book closing instead of using the search function when the inventory key was pressed. 
